### ISSUE TITLE
Script doesn't install NPM while installing nodejs

### ISSUE THREAD

**Issue by shembane** [chirag350/dashactyl-install-script#1]
I ran the script on a VPS and all was working fine until the nodejs install finished and gave me this:

![image](https://user-images.githubusercontent.com/28643762/130315986-319b430f-e871-4209-9f31-b191857745bc.png)

It looks like the script doesn't install NPM and than fails when trying to run the rest of the script

**Comment by FatGrizzly** [comment]
Hello @shembane 
Can you also attach the log file?(dashactyl-script.log)

**Comment by shembane** [comment]
> 
> 
> Hello @shembane
> Can you also attach the log file?(dashactyl-script.log)

[dashactyl log.txt](https://github.com/chirag350/dashactyl-install-script/files/7025213/dashactyl.log.txt)

Here you go

**Comment by chirag350** [comment]
Fixed in [3f3dc6f](https://github.com/chirag350/dashactyl-install-script/commit/97e8635e8bb74a1618823cf553c05285557d1507)
